/** Quotes about reading, knowledge, and self-development for the access request success message */
export const KNOWLEDGE_QUOTES = [
  'The more that you read, the more things you will know. The more that you learn, the more places you\'ll go.',
  'A reader lives a thousand lives before he dies. The man who never reads lives only one.',
  'Books are a uniquely portable magic.',
  'There is no frigate like a book to take us lands away.',
  'The reading of all good books is like a conversation with the finest minds of past centuries.',
  'Today a reader, tomorrow a leader.',
  'Reading is to the mind what exercise is to the body.',
  'One book, one pen, one child, and one teacher can change the world.',
  'I have always imagined that Paradise will be a kind of library.',
  'The only way to do great work is to love what you do.',
  'The mind is not a vessel to be filled but a fire to be kindled.',
  'An investment in knowledge pays the best interest.',
  'Develop a passion for learning. If you do, you will never cease to grow.',
  'Live as if you were to die tomorrow. Learn as if you were to live forever.',
  'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.',
  'Learning never exhausts the mind.',
  'The roots of education are bitter, but the fruit is sweet.',
  'Knowledge is power. Information is liberating.',
  'The beautiful thing about learning is that nobody can take it away from you.',
  'Reading gives us someplace to go when we have to stay where we are.',
  'A book is a dream that you hold in your hand.',
  'So many books, so little time.',
  'There is no greater agony than bearing an untold story inside you.',
  'Words are our most inexhaustible source of magic.',
  'That\'s the thing about books. They let you travel without moving your feet.',
  'Books are the quietest and most constant of friends.',
  'Reading is a basic tool in the living of a good life.',
  'A library is not a luxury but one of the necessities of life.',
  'The world belongs to those who read.',
  'We read to know we\'re not alone.',
  'No two persons ever read the same book.',
  'You can never get a cup of tea large enough or a book long enough to suit me.',
  'I cannot live without books.',
  'A room without books is like a body without a soul.',
  'Reading is escape, and the opposite of escape; it\'s a way to make contact with reality.',
  'The books that help you most are those which make you think that most.',
  'Think before you speak. Read before you think.',
  'Some books leave us free and some books make us free.',
  'To learn to read is to light a fire; every syllable that is spelled out is a spark.',
  'Read. Read. Read. Just don\'t read one type of book.',
  'The person who does not read has no advantage over the person who cannot read.',
  'You don\'t have to burn books to destroy a culture. Just get people to stop reading them.',
  'There is creative reading as well as creative writing.',
  'Books are mirrors: you only see in them what you already have inside you.',
  'A book is the most effective weapon against intolerance and ignorance.',
  'Reading is a conversation. All books talk. But a good book listens as well.',
  'Once you learn to read, you will be forever free.',
  'Reading brings us unknown friends.',
  'In the case of good books, the point is not to see how many of them you can get through, but rather how many can get through to you.',
  'The journey of a lifetime starts with the turning of a page.',
  'Books are the plane, and the train, and the road. They are the destination, and the journey.',
  'Reading is a discount ticket to everywhere.',
  'A book is a device to ignite the imagination.',
  'The man who does not read has no advantage over the man who cannot read.',
  'You may have tangible wealth untold; caskets of jewels and coffers of gold. Richer than I you can never be—I had a mother who read to me.',
  'If you don\'t like to read, you haven\'t found the right book.',
  'Reading is an act of civilization; it\'s one of the greatest acts of civilization because it takes the free raw material of the mind and builds castles of possibilities.',
  'There are perhaps no days of our childhood we lived so fully as those we spent with a favorite book.',
  'A house without books is like a room without windows.',
  'The worth of a book is to be measured by what you can carry away from it.',
  'A good book is an event in my life.',
  'A great book should leave you with many experiences, and slightly exhausted at the end.',
  'The more you read, the more things you will know. The more that you learn, the more places you\'ll go.',
  'Books are the treasured wealth of the world and the fit inheritance of generations.',
  'Fiction is the truth inside the lie.',
  'No matter how busy you may think you are, you must find time for reading, or surrender yourself to self-chosen ignorance.',
  'Reading is the sole means by which we slip, involuntarily, often helplessly, into another\'s skin.',
  'The goal of education is the advancement of knowledge and the dissemination of truth.',
  'Education is what remains after one has forgotten what one has learned in school.',
  'The only thing that you absolutely have to know is the location of the library.',
  'Let us remember: One book, one pen, one child, and one teacher can change the world.',
  'I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.',
  'Be as careful of the books you read as of the company you keep.',
  'Books serve to show a man that those original thoughts of his aren\'t very new after all.',
  'The love of learning, the sequestered nooks, and all the sweet serenity of books.',
  'A library is the delivery room for the birth of ideas.',
  'Libraries will get you through times of no money better than money will get you through times of no libraries.',
  'A book is a garden, an orchard, a storehouse, a party, a company by the way, a counselor, a multitude of counselors.',
  'Reading is departure and arrival.',
  'Books are the compasses and telescopes and sextants and charts which other men have prepared to help us navigate the dangerous seas of human life.',
] as const;

export function getRandomQuote(): string {
  return KNOWLEDGE_QUOTES[Math.floor(Math.random() * KNOWLEDGE_QUOTES.length)];
}
